import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1731417282953 implements MigrationInterface {
    name = 'AutoGeneratedMigration1731417282953'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subscription_plans" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ADD "name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ALTER COLUMN "description" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ALTER COLUMN "discountedPrice" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ALTER COLUMN "features" DROP NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subscription_plans" ALTER COLUMN "features" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ALTER COLUMN "discountedPrice" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ALTER COLUMN "description" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ADD "name" character varying(255) NOT NULL`);
    }

}
