import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1731412295365 implements MigrationInterface {
    name = 'AutoGeneratedMigration1731412295365'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "userToRole" DROP CONSTRAINT "FK_76679a35f47ae90ae9139d3666b"`);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text NOT NULL, "price" double precision NOT NULL, "discountedPrice" double precision NOT NULL, "duration" integer NOT NULL, "features" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "userToRole" DROP COLUMN "roleId"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "userToRole" ADD "roleId" uuid`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`ALTER TABLE "userToRole" ADD CONSTRAINT "FK_76679a35f47ae90ae9139d3666b" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
