import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1731217545643 implements MigrationInterface {
    name = 'AutoGeneratedMigration1731217545643'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "userDetails" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "phoneNumber" character varying(20)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "phoneNumber"`);
        await queryRunner.query(`ALTER TABLE "userDetails" ADD "phoneNumber" character varying(20)`);
    }

}
