import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigration1731267842496 implements MigrationInterface {
    name = 'AutoGeneratedMigration1731267842496'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" ADD "isEmailVerified" boolean NOT NULL DEFAULT false`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "isEmailVerified"`);
    }

}
